version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: gorm.io/gorm
    versions:
    - 1.21.1
    - 1.21.2
    - 1.21.3
    - 1.21.4
    - 1.21.5
    - 1.21.6
    - 1.21.7
